### ISSUE TITLE
AttributeError: 'module' object has no attribute 'DaemonContext'

### ISSUE THREAD

**Issue by cjdupreez** [hvqzao/liffy#1]
Hi Marcin, first off, thanks for a great tool. I'm using it at the moment and seem to be having an issue with the DaemonContext. 

Command: liffy.py --url https://10.1.1.5/section.php?page= --data

All goes well until it reaches the web serve portion:

[2016-10-08 16:44:04.270587] Starting Web Server ... 
[2016-10-08 16:44:04.270603] ...................................................................... 
Traceback (most recent call last):
  File "http_server.py", line 10, in <module>
    daemon_context = daemon.DaemonContext()
AttributeError: 'module' object has no attribute 'DaemonContext'
[2016-10-08 16:44:05.050464] Press Enter To Continue When Your Metasploit Handler is Running ...

Any thoughts on what might be causing the error?

**Comment by hvqzao** [comment]
Hi cjdupreez,
It is not my code. It was originally released under GPL license at https://github.com/rotlogix/liffy. I've noticed later that it is no longer available there, so I decided to establish a local mirror. I'm not supporting its development. I'm sorry. You can check if someone else has established a mirror or is actively developing liffy's fork. Take care!

**Comment by cjdupreez** [comment]
No worries, thanks for getting back to me.

Regards,
-Cornel.

**Comment by ajdumanhug** [comment]
pip install python-daemon is the solution for your error. If you executed pip install daemon then you just downloaded the daemon.pyc
